services:
  backend:
    command: ["npm", "start"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  worker:
    command: ["node", "worker.js"]
