apiVersion: v1
kind: Secret
metadata:
  name: ai-assistant-secrets
  namespace: ai-assistant
type: Opaque
data:
  postgres-password: cGFzc3dvcmQ= # password
  openai-api-key: c2stb3ItdjEtNDc1NTQ1MGU2MzU3ZDE0Y2NjOTcyYjllNDgxN2I4ZDkyYzg2M2VlZmMwMDAwY2MxNWI1ZDQxYmI2MGZhZTk1MA==
  gemini-api-key: QUl6YVN5QzVBTF9WdEZTLUx2QjFJX1d5VzR6ZFNNZTZsdUQ2WGFR
